export const EFFECTS = {
    'all': [],
    'beast': ['+10% chance of Critical Hit', 'Muscle +20'],
    'bug': ['Weapon Damage +25%', 'Maximum MP +25%'],
    'constellation': ['+10% chance of Spell Critical Hit', 'Mysticality +20'],
    'construct': ['+3 Moxie Stats Per Fight', '+25 Spell Damage'],
    'demon': ['+25 Hot Damage', '+50% Gear Drops'],
    'dude': ['+25 Cold Damage', 'Moxie +50%'],
    'elemental': ['Serious Hot Resistance (+3)', '+25 Damage to Stench Spells'],
    'elf': ['+5 Stats Per Fight', '+75% Candy Drops'],
    'fish': ['+50% Meat from Monsters', '+25 Damage to Spooky Spells'],
    'goblin': ['+25 Stench Damage', 'Mysticality +50%'],
    'hippy': ['Serious Stench Resistance (+3)', 'Damage Reduction: 10'],
    'hobo': ['+3 Mysticality Stats Per Fight', '+25 Damage to Hot Spells'],
    'humanoid': ['Spell Damage +25%', 'Moxie +20'],
    'horror': ['Serious Spooky Resistance (+3)', 'Maximum HP +50'],
    'mer-kin': ['+25% Item Drops from Monsters', '+25 Damage to Sleaze Spells'],
    'orc': ['Serious Sleaze Resistance (+3)', 'Maximum MP +25'],
    'penguin': ['+3 Muscle Stats Per Fight', '+25 Damage to Cold Spells'],
    'pirate': ['+50% Booze Drops from Monsters', '+25 Sleaze Damage'],
    'plant': ['Combat Initiative +50%', '+50% Maximum HP'],
    'slime': ['Serious Cold Resistance (+3)', 'Damage Absorption +50'],
    'undead': ['+25 Spooky Damage', 'Muscle +50%'],
    'weird': ['+50% Food Drops from Monsters', 'Weapon Damage +25']
}
